# Jekyll テーマ設定
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# サイト設定
title: Takumi Kobayashi
description: Takumi Kobayashi's Resume
url: https://yatami0.github.io
baseurl: "/takobayashi.github.io"

# 追加設定
markdown: kramdown